# Site settings
title: "I'll fix it when it's not broken"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Personal website of @saxophonicle
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrishaynie.com" # the base hostname & protocol for your site
twitter_username: saxophonicle
github_username:  saxophonicle

# Build settings
markdown: kramdown
